name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Set status
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/statuses/:sha
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          sha: ${{ github.event.pull_request.head.sha }}
          state: ${{ job.status }}
          target_url: ${{ github.run_number }}
          description: "The tests have completed"
          context: Test